network_type: ???
max_epochs: ???
num_parts: ???
lr: 0.001
batch_size: 16
num_workers: 4

# Loss weights
loss_weight: 
  seg_loss: 1.0
  npcs_loss: 10.0
  naocs_loss: 1.0
  heatmap_loss: 5.0
  unitvec_loss: 5.0
  axis_loss: 0.2
  joint_loss: 1.0
