defaults:
  - default
  - _self_ # https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order

dataset_dir: "/home/hanxiao/projects/rrg-msavva/hanxiao/proj-motionnet/Dataset/eyeglasses_ancsh"
result_dir: "/scratch/hanxiao/proj-motionnet/ancsh_output/npcs"
