version: "1.0"

dataset_dir: ??? # path to datasets folder
result_dir: ??? # path to result folder

preprocess:
  input_dir: "${paths.dataset_dir}"
  output_dir: "${paths.result_dir}/preprocess"
  tmp_dir: "${paths.preprocess.output_dir}/tmp"

  stage1:
    input: paths # overwrite based on dataset selection at runtime
    tmp_output:
      input_files: "input_files.csv"
      rest_state_data: "rest_state.json"
      rest_state_mesh: "rest_state.ply"
      pcd_camera: "pcd_camera_%05d.ply"
      pcd_rest_state: "pcd_rest_state_%05d.ply"
      normalize_info: "normalize_info.json"
      part_order: "part_order.json"
      joint_params: "joint_params.json"

  output:
    train: "${paths.preprocess.result_dir}/train.h5"
    val: "${paths.preprocess.result_dir}/val.h5"
    test: "${paths.preprocess.result_dir}/test.h5"
    