defaults:
  - default
  - _self_ # https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order

dataset_dir: "/localhome/yma50/Development/ANCSH-pytorch/datasets/motionnet"
result_dir: "/localhome/yma50/Development/ANCSH-pytorch/results"

