version: "v1.0"

optimization_result_path: ???
num_parts: ???

defaults:
  - paths: ???
  - evaluation: default
  - _self_ # https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order

# hydra configuration log output dir
hydra:
  run:
    dir: "${paths.evaluation.output_dir}/logs/${now:%Y-%m-%d}/${now:%H-%M-%S}"