version: "v1.0"

test: ???
model_frequency: 5000
log_frequency: 10
inference_model: ???

defaults:
  - paths: ???
  - network: ???
  - _self_ # https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order

# hydra configuration log output dir
hydra:
  run:
    dir: "config_logs/network/${now:%Y-%m-%d}/${now:%H-%M-%S}"
