version: "v1.0"

device: "cuda:0"

eval_only: false

train:
  save_frequency: 500
  log_frequency: 10
  random_seed: 42

test:
  split: "val"


defaults:
  - paths: ???
  - network: ???
  - _self_ # https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order

# hydra configuration log output dir
hydra:
  run:
    dir: "${paths.network.output_dir}/logs/${now:%Y-%m-%d}/${now:%H-%M-%S}"
