version: "v1.0"

defaults:
  - paths: paths
  - _self_ # https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order

# hydra configuration log output dir
hydra:
  run:
    dir: "config_logs/preprocess/${now:%Y-%m-%d}/${now:%H-%M-%S}"
