version: "v1.0"

debug: false
show: false
export: false
num_workers: 8

defaults:
  - dataset: sapien
  - paths: ???
  - _self_ # https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order

settings:
  categories: []
  object_ids: []
  articulation_ids: []
  stage1:
    process: true
  stage2:
    process: true
    train_percent: 0.6
    split_seed: 1

params:
  joint_association_threshold: 0.2

# hydra configuration log output dir
hydra:
  run:
    dir: "${paths.preprocess.output_dir}/logs/${now:%Y-%m-%d}/${now:%H-%M-%S}"
