version: "v1.0"

debug: true
show: false
export: false
num_workers: 1

defaults:
  - dataset: motionnet
  - paths: ???
  - _self_ # https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order

settings:
  categories: ['OneDoor']
  object_ids: []
  object_ids_path: "${paths.dataset_dir}/object_id.csv"
  articulation_ids: []
  stage1:
    process: true
  stage2:
    process: true
    train_percent: 0.6
    split_seed: 1
    split_on: "objectId" # or articulationId, frameId

params:
  joint_association_threshold: 0.2

# hydra configuration log output dir
hydra:
  run:
    dir: "${paths.preprocess.output_dir}/logs/${now:%Y-%m-%d}/${now:%H-%M-%S}"
